@host= http://localhost:3000/api

###
GET {{ host }}/key

###
POST {{ host }}/signin
Content-Type: application/json
api-key: a2IyL0wy_

{
    "email": "dario0@mail.com",
    "password": "ANAbanana3000$"
}

###
GET {{ host }}/users/1
api-key: a2IyL0wy_

###
POST {{ host }}/users
Content-Type: application/json
api-key: a2IyL0wy_

{
    "name": "Dario",
    "last_name": "Martinez",
    "email": "dario0@mail.com",
    "password": "ANAbanana3000$",
    "confirm_password": "ANAbanana3000$",
    "birthday": "1999-09-04"
}

###
PUT {{ host }}/users/1
Content-Type: application/json
api-key: DdOVfsEUu

{
    "name": "Gustavo",
    "last_name": "Martinez",
    "email": "dario0@mail.com",
    "password": "ANAbanana3000$",
    "confirm_password": "ANAbanana3000$",
    "birthday": "1999-09-04"
}

###
DELETE {{ host }}/users/1
api-key: DdOVfsEUu